// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AttachTunnel(arg1:string,arg2:string):Promise<db.ServerTunnel>;

export function CreateBackup(arg1:string):Promise<db.Backup>;

export function CreateJavaAndBedrockTunnels(arg1:string):Promise<Array<db.ServerTunnel>>;

export function CreatePlayitAccount(arg1:string,arg2:string):Promise<db.PlayitAccount>;

export function CreateServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<db.Server>;

export function CreateTunnel(arg1:string,arg2:string):Promise<db.ServerTunnel>;

export function DeleteMod(arg1:string,arg2:string):Promise<void>;

export function DeletePlayitAccount(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteServerRecord(arg1:string):Promise<void>;

export function DetachTunnel(arg1:string,arg2:string):Promise<void>;

export function DetectServerDirectory(arg1:string):Promise<Record<string, string>>;

export function GetGeyserStatus(arg1:string):Promise<Record<string, any>>;

export function GetServer(arg1:string):Promise<db.Server>;

export function GetServerIcon(arg1:string):Promise<string>;

export function GetServerLogs(arg1:string):Promise<string>;

export function GetServerMetrics(arg1:string,arg2:number):Promise<Array<db.ServerMetric>>;

export function GetServerStorage(arg1:string):Promise<Record<string, any>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTunnelStatus(arg1:string):Promise<Array<db.ServerTunnel>>;

export function ImportServerFromPath(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<db.Server>;

export function ImportServerFromZip(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<db.Server>;

export function InstallMods(arg1:string,arg2:Array<string>):Promise<void>;

export function InstallOrUpdateGeyser(arg1:string):Promise<Record<string, any>>;

export function ListAppLogs():Promise<Array<db.AppLog>>;

export function ListBackups(arg1:string):Promise<Array<db.Backup>>;

export function ListMods(arg1:string):Promise<Record<string, any>>;

export function ListPlayitAccounts():Promise<Array<any>>;

export function ListServers():Promise<Array<db.Server>>;

export function ListTunnels():Promise<Array<db.ServerTunnel>>;

export function Quit():Promise<void>;

export function RescanTunnel(arg1:string):Promise<Array<db.ServerTunnel>>;

export function RestartServer(arg1:string):Promise<Record<string, string>>;

export function RestoreBackup(arg1:string):Promise<Record<string, string>>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SendServerCommand(arg1:string,arg2:string):Promise<string>;

export function Show():Promise<void>;

export function StartPlayitClaim():Promise<Record<string, string>>;

export function StartServer(arg1:string):Promise<db.Server>;

export function StartStreamingLogs(arg1:string):Promise<void>;

export function StartStreamingPlayitLogs(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<Record<string, string>>;

export function StopStreamingLogs(arg1:string):Promise<void>;

export function StopStreamingPlayitLogs(arg1:string):Promise<void>;

export function UpdateBackupSchedule(arg1:string,arg2:boolean,arg3:number,arg4:number):Promise<db.Server>;

export function UpdateServerSettings(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:number):Promise<db.Server>;

export function UpdateSettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadServerIcon(arg1:string,arg2:string):Promise<void>;
