// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachTunnel(arg1, arg2) {
  return window['go']['main']['App']['AttachTunnel'](arg1, arg2);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateJavaAndBedrockTunnels(arg1) {
  return window['go']['main']['App']['CreateJavaAndBedrockTunnels'](arg1);
}

export function CreatePlayitAccount(arg1, arg2) {
  return window['go']['main']['App']['CreatePlayitAccount'](arg1, arg2);
}

export function CreateServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateServer'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTunnel(arg1, arg2) {
  return window['go']['main']['App']['CreateTunnel'](arg1, arg2);
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DeletePlayitAccount(arg1) {
  return window['go']['main']['App']['DeletePlayitAccount'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteServerRecord(arg1) {
  return window['go']['main']['App']['DeleteServerRecord'](arg1);
}

export function DetachTunnel(arg1, arg2) {
  return window['go']['main']['App']['DetachTunnel'](arg1, arg2);
}

export function DetectServerDirectory(arg1) {
  return window['go']['main']['App']['DetectServerDirectory'](arg1);
}

export function GetGeyserStatus(arg1) {
  return window['go']['main']['App']['GetGeyserStatus'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServerIcon(arg1) {
  return window['go']['main']['App']['GetServerIcon'](arg1);
}

export function GetServerLogs(arg1) {
  return window['go']['main']['App']['GetServerLogs'](arg1);
}

export function GetServerMetrics(arg1, arg2) {
  return window['go']['main']['App']['GetServerMetrics'](arg1, arg2);
}

export function GetServerStorage(arg1) {
  return window['go']['main']['App']['GetServerStorage'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTunnelStatus(arg1) {
  return window['go']['main']['App']['GetTunnelStatus'](arg1);
}

export function ImportServerFromPath(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ImportServerFromPath'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ImportServerFromZip(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ImportServerFromZip'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InstallMods(arg1, arg2) {
  return window['go']['main']['App']['InstallMods'](arg1, arg2);
}

export function InstallOrUpdateGeyser(arg1) {
  return window['go']['main']['App']['InstallOrUpdateGeyser'](arg1);
}

export function ListAppLogs() {
  return window['go']['main']['App']['ListAppLogs']();
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListMods(arg1) {
  return window['go']['main']['App']['ListMods'](arg1);
}

export function ListPlayitAccounts() {
  return window['go']['main']['App']['ListPlayitAccounts']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RescanTunnel(arg1) {
  return window['go']['main']['App']['RescanTunnel'](arg1);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendServerCommand(arg1, arg2) {
  return window['go']['main']['App']['SendServerCommand'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function StartPlayitClaim() {
  return window['go']['main']['App']['StartPlayitClaim']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StartStreamingLogs(arg1) {
  return window['go']['main']['App']['StartStreamingLogs'](arg1);
}

export function StartStreamingPlayitLogs(arg1) {
  return window['go']['main']['App']['StartStreamingPlayitLogs'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function StopStreamingLogs(arg1) {
  return window['go']['main']['App']['StopStreamingLogs'](arg1);
}

export function StopStreamingPlayitLogs(arg1) {
  return window['go']['main']['App']['StopStreamingPlayitLogs'](arg1);
}

export function UpdateBackupSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBackupSchedule'](arg1, arg2, arg3, arg4);
}

export function UpdateServerSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateServerSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3, arg4);
}

export function UploadServerIcon(arg1, arg2) {
  return window['go']['main']['App']['UploadServerIcon'](arg1, arg2);
}
